djangoEg/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^polls/',include('polls.urls')),
	url(r'^music/',include('music.urls')),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url

from . import views

app_name = 'music'

urlpatterns = [
	url(r'^$',views.IndexView.as_view(),name='index'),
	url(r'^register/$',views.UserFormView.as_view(),name='register'),

	#/music/id
	url(r'^(?P<pk>[0-9]+)$',views.DetailView.as_view(),name='detail'),

	#/music/favorite
	# url(r'^(?P<album_id>[0-9]+)/favorite$',views.favorite,name='favorite'),
	url(r'album/add/$',views.AlbumCreate.as_view(),name='album-add'),
	url(r'^album/(?P<pk>[0-9]+)$',views.AlbumUpdate.as_view(),name='album-update'),
	url(r'^album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(),name='album-delete'),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=50)
	album_logo = models.CharField(max_length=1000)

	def get_absolute_url(self):
		return reverse('music:detail',kwargs = {'pk':self.pk})

	def __str__(self):
		return self.album_title + ' - ' + self.artist


class Song(models.Model):
	album = models.ForeignKey(Album,on_delete = models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default = False)

	def __str__(self):
		return self.song_title

polls/models.py
from django.db import models

# Create your models here.

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget =  forms.PasswordInput)
	class Meta:
	 	model = User
	 	fields = ['username','email','password']

music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View

from .models import Album
from .forms import UserForm

class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name = 'all_albums'

	def get_queryset(self):
		return Album.objects.all()


class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/detail.html'

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist','album_title','genre','album_logo']	

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')

class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html'

	def get(self, request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form = self.form_class(request.POST)	

		if form.is_valid():
			user = form.save(commit = False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			user = authenticate(username = username, password = password)

			if user is not None:
				if user.is_active:
					login(request,user)
					# request.user.username
					return redirect('music:index')
		return render(request,self.template_name,{'form':form})
			

polls/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def index(request):
	return HttpResponse("hi this is response view")

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add Album {% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}	
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="mutlipart/form-data">
						{% csrf_token %}
						{% include 'music/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-3 col-sm-12">
								<button type="submit" class="btn btn-success">Submit</button>	
							</div>
						</div>	
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}	
			MusicPedia
		{% endblock %}
	</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/
	font-awesome.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

	<link rel="stylesheet" type="text/css" href="{% static 'music/css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'music:index' %}">MusicPedia</a>
			</div>

			<div class="collapse navbar-collapse" id="topNavBar">
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="{% url 'music:index' %}">
							<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
						</a>
					</li>

					<li class=""> 
						<a href="#">
							<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
						</a>	
					</li>
				</ul>

				<form class="navbar-form navbar-left" role="search" method="get" action="#">
					<div class="form-group">
						<input type="text" name="search" class="form-control" value="">
					</div>
					<button type="submit" class="btn btn-default">Search</button>
				</form>

				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="{% url 'music:album-add' %}">
							<span class="glyphicon glyphicon-plus" aria-hidden="true">&nbsp;Add Album</span>
						</a>
					</li>	

					<li>
						<a href="">
							<span class="glyphicon glyphicon-off" aria-hidden="true">&nbsp;Logout</span>
						</a>
					</li>	
				</ul>	
			</div>	
		</div>
	</nav>

	{% block body %}	
	{% endblock %}
</body>
</html>

music/templates/music/detail - Copy.html
{% extends 'music/base.html' %}
{% block title %} Album Detail {% endblock %}
{% block body %}	
	<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3>{{album.id}} - {{album.album_title}} - {{album.genre}} </h3>
							<img src="{{album.album_logo}}" width="150px">
							<h4>- {{album.artist}}</h4>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="panel panel-primary">
						<div class="panel-heading">
							All Song Listing
						</div>

						<div class="panel-body">
							<form action="{% url 'music:favorite' album.id %}" method="post">
								{% csrf_token %}
								{% for song in album.song_set.all %}
									<input type="radio" name="song"  id="song{{ forloop.counter }}" value="{{ song.id }}">
									<label for ="song{{ forloop.counter }}"> {{song.song_title}}
									{% if song.is_favorite %}
										<i class="fa fa-star" aria-hidden="true" style="color: gold"></i>
									{% endif %}
									</label>
									<br>
								{% endfor %}
								<input type="submit" name="" value="Favorite" class="btn btn-warning">
							</form>	
						</div>
					</div>
				</div>	

				{% if error_message %}
					<div class="col-md-6">
						<div class="panel panel-primary">
							<div class="panel-heading">
								Errors
							</div>

							<div class="panel-body">
								<div class="alert alert-danger">
	  								<strong>Error!</strong> You have not selected any song
								</div>
							</div>						
						</div>
					</div>	
				{% endif %}
			</div>
	</div>
{% endblock %}

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} Album Detail {% endblock %}
{% block body %}	
	<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3>{{album.id}} - {{album.album_title}} - {{album.genre}} </h3>
							<img src="{{album.album_logo.url}}" width="150px">
							<h4>- {{album.artist}}</h4>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="panel panel-primary">
						<div class="panel-heading">
							All Song Listing
						</div>

						<div class="panel-body">
								{% csrf_token %}
								{% for song in album.song_set.all %}
									<input type="radio" name="song"  id="song{{ forloop.counter }}" value="{{ song.id }}">
									<label for ="song{{ forloop.counter }}"> {{song.song_title}}
									</label>
									<br>
								{% endfor %}
							
						</div>
					</div>
				</div>	

				{% if error_message %}
					<div class="col-md-6">
						<div class="panel panel-primary">
							<div class="panel-heading">
								Errors
							</div>

							<div class="panel-body">
								<div class="alert alert-danger">
	  								<strong>Error!</strong> You have not selected any song
								</div>
							</div>						
						</div>
					</div>	
				{% endif %}
			</div>
	</div>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
	  			<span class="text-danger small">
	  				{{ field.errors }}
	  			</span>

			<label class="control-label col-sm-3">{{ field.label_tag }}</label>
			<div class="col-sm-9">{{ field }}</div>
		</div>
	</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}	
	<h3> All albums </h3>
	{% if all_albums %}
	<ul>
		{% for album in all_albums %}
		<li>
			<a href="{% url 'music:detail' album.id %}">{{album.album_title}}</a>
			<form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
				{% csrf_token %}
				<input type="hidden" name="album_id" value="{{ album.id }}" />
				<button type="submit" class="btn btn-default btn-sm">
					<span class="glphyicon glphyicon-trash"></span>
				</button>
			</form>
		</li>
		{% endfor %}	
	</ul>
	{% else %}
		<h3> No albums </h3>
	{% endif %}
{% endblock %}		

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register {% endblock %}


{% block body %}	
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Create New Account
				</div>	
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'music/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-3 col-sm-12">
								<button type="submit" class="btn btn-success">Submit</button>	
							</div>
						</div>	
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}